### ISSUE TITLE
extraction code error.

### ISSUE THREAD

**Issue by MollyDai** [HolmesShuan/OISR-PyTorch#1]
When I download the training dataset, the system prompts the extraction code(ij6f) error.

**Comment by HolmesShuan** [comment]
Sorry for the mistake, link updated. If it failed again, you may try the OneDrive link.

**Comment by MollyDai** [comment]
thanks a lot

**Comment by HolmesShuan** [comment]
@zhanghuan18332552065 I will reopen this issue if any new bugs are reported. Thanks in advance.
