### ISSUE TITLE
about test path

### ISSUE THREAD

**Issue by Jee-King** [HolmesShuan/OISR-PyTorch#4]
Thanks for your sharing.、

`python main.py --data_test Set5+Set14+B100+Urban100+DIV2K --data_range 801-900 --scale 2 --test_only --ext bin --dir_data /home/data/ --n_resblocks 8 --n_feats 122 --pre_train ./RK2-m/x2.pt --gpu-id 4,5,6,7 --chop --n_GPUs 4 --save_results
`

Is the dataset Set5 path format supposed to be `/home/data/benchmark/Set5/HR` and  `/home/data/benchmark/Set5/LR_bicubic/X2`?

**Comment by Jee-King** [comment]
I found that the image naming problem caused the image not to be found.
Thanks, I close it.

**Comment by HolmesShuan** [comment]
:) Thanks for your interest.
